name: Backdoor Create and Decode Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cryptography

    - name: Create backdoor file
      run: |
        python create_backdoor.py

    - name: Decode backdoor file
      run: |
        python decode_backdoor.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: backdoor-artifacts
        path: |
          signed_bundle.backdoor
          decoded.mobileprovision
        retention-days: 7

    - name: Commit backdoor file
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add signed_bundle.backdoor decoded.mobileprovision
        git commit -m "Add generated backdoor and decoded files" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}