name: Backdoor Create and Decode Workflow

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Clear pip cache
      run: |
        pip cache purge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cryptography pyOpenSSL

    - name: Verify dependencies
      run: |
        pip show cryptography
        pip show pyOpenSSL
        python -c "import cryptography; print(cryptography.__version__)"
        python -c "import OpenSSL; print(OpenSSL.__version__)"

    - name: Create backdoor file
      id: create-backdoor
      run: |
        python create_backdoor.py
      working-directory: .

    - name: Decode backdoor file
      id: decode-backdoor
      run: |
        python verify_backdoor.py  # Assuming this is the correct name
      working-directory: .

    - name: Check for output directories
      run: |
        ls -l backdoor_output/ || echo "No backdoor_output directory found"
        ls -l extracted_output/ || echo "No extracted_output directory found"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: backdoor-artifacts
        path: |
          backdoor_output/**/*
          extracted_output/**/*
        if-no-files-found: ignore  # Prevent failure if no files are found
        retention-days: 7

    - name: Commit backdoor and decoded files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        if [ -d "backdoor_output" ]; then git add backdoor_output/*; fi
        if [ -d "extracted_output" ]; then git add extracted_output/*; fi
        git commit -m "Add generated backdoor and decoded files" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}